# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['src\\app.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('trackdb', 'trackdb'),
        ('src\\gt7db\\gt7_car.csv', 'src\\gt7db'),
        ('src\\gt7db\\gt7_layouts.csv', 'src\\gt7db'),
        ('src\\gt7db\\gt7_venues.csv', 'src\\gt7db'),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'accelerate',
        'bitsandbytes',
        'datasets',
        'IPython',
        'ipykernel',
        'jupyter',
        'jupyter_client',
        'jupyter_core',
        'keras',
        'matplotlib',
        'notebook',
        'psycopg',
        'psycopg2',
        'pytest',
        'sqlalchemy',
        'tensorflow',
        'torch',
        'torchaudio',
        'torchvision',
        'transformers',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='GT7-Machine-Learning-Tool',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
